---
os: linux
dist: focal
language: php

branches:
  only:
    - master
    - /^(v)?\d+\.\d+(\.\d+)?(-\S*)?$/

git:
  depth: 10
  quiet: true

env:
  global:
    - XDEBUG_MODE=coverage

jobs:
  fast_finish: true
  allow_failures:
    - php: 8.0
  include:
    - &STANDARD_TEST_JOB
      stage: "Code style, lint and unit-tests"
      php: 7.3
      install:
        - (composer self-update; true)
        - composer install --no-progress --no-suggest --no-interaction --no-cache
      script:
        - export TRAVIS_PULL_REQUEST TRAVIS_COMMIT_RANGE
        - ./dev-tools/php-cs-check.sh
        - composer check:analyse
        - composer check:test
      after_success:
        - bash <(curl -s https://codecov.io/bash) -s ./build/

    - &STANDART_UNIT_TEST_JOB
      <<: *STANDARD_TEST_JOB
      stage: "Unit tests other php versions"
      php: 7.4
      script:
        - composer check:test

    -
      <<: *STANDART_UNIT_TEST_JOB
      php: 8.0
